### ISSUE TITLE
Should we use this issue centre for QA ?

### ISSUE THREAD

**Issue by avivday** [avivday/LogiNow#1]
Should we use this issue centre for QA?
Basically asking this just to decide if GitHub Issues centre is convenient enough for us (It's awesome but we never used it properly).

What's your thoughts?

**Comment by aviorp** [comment]
I totaly agree.
I think that when we get to the QA part, we should do it together online using Microsoft Teams.

P.S
If you asking here, and then sending me a WhatsApp message asking me to read this question, it's useful 🤣

**Comment by hassideitan** [comment]
סוף סוף מצליח להתחבר!
נעשה פגישות בטימס!

נ.ב
ותכתבו בעברית כבר

**Comment by avivday** [comment]
מדהים הגענו להחלטה חחח
קדימה לעבודה - סוגר את הדיון 😄 
איתן מחכים לבקשות הפיצ'רים שהעלית בפגישה היום!
